FROM node:10.7-alpine
WORKDIR /pngr/react
COPY . .
RUN npm install
RUN npm run build -o app

# multistage build...
# this runs a lil nginx instance to serve the app
FROM nginx:alpine
COPY --from=0 /pngr/react/build /usr/share/nginx/html