// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePostByIDs(ctx context.Context, arg DeletePostByIDsParams) error
	FindPostByIDs(ctx context.Context, arg FindPostByIDsParams) (Post, error)
	FindPostsByAuthor(ctx context.Context, authorID int64) ([]Post, error)
	FindUserByEmail(ctx context.Context, lower string) (User, error)
	FindUserByVerificationCode(ctx context.Context, verification string) (User, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
}

var _ Querier = (*Queries)(nil)
