// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateReset(ctx context.Context, arg CreateResetParams) (Reset, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePostByIDs(ctx context.Context, arg DeletePostByIDsParams) error
	DeleteResetsForUser(ctx context.Context, userID int64) error
	FindPostByIDs(ctx context.Context, arg FindPostByIDsParams) (Post, error)
	FindPostsByAuthor(ctx context.Context, authorID int64) ([]Post, error)
	FindResetByCode(ctx context.Context, code string) (Reset, error)
	FindUserByEmail(ctx context.Context, lower string) (User, error)
	FindUserByID(ctx context.Context, id int64) (User, error)
	FindUserByVerificationCode(ctx context.Context, verification string) (User, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
}

var _ Querier = (*Queries)(nil)
