// Code generated by sqlc. DO NOT EDIT.
// source: user.sql

package db

import (
	"context"
	"time"
)

const create = `-- name: Create :one
INSERT INTO users (email, salt, pass, status, verification) VALUES (LOWER($1), $2, $3, $4, $5) RETURNING id, name, email, pass, salt, status, verification, created_at, updated_at
`

type CreateParams struct {
	Lower        string     `json:"lower"`
	Salt         string     `json:"salt"`
	Pass         string     `json:"pass"`
	Status       UserStatus `json:"status"`
	Verification string     `json:"verification"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (User, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.Lower,
		arg.Salt,
		arg.Pass,
		arg.Status,
		arg.Verification,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Pass,
		&i.Salt,
		&i.Status,
		&i.Verification,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findByEmail = `-- name: FindByEmail :one
SELECT id, name, email, pass, salt, status, verification, created_at, updated_at FROM users WHERE email = LOWER($1) LIMIT 1
`

func (q *Queries) FindByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRowContext(ctx, findByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Pass,
		&i.Salt,
		&i.Status,
		&i.Verification,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findByVerificationCode = `-- name: FindByVerificationCode :one
SELECT id, name, email, pass, salt, status, verification, created_at, updated_at FROM users WHERE verification = $1 LIMIT 1
`

func (q *Queries) FindByVerificationCode(ctx context.Context, verification string) (User, error) {
	row := q.db.QueryRowContext(ctx, findByVerificationCode, verification)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Pass,
		&i.Salt,
		&i.Status,
		&i.Verification,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStatus = `-- name: UpdateStatus :exec
UPDATE users SET status = $1, updated_at = $2 WHERE id = $3
`

type UpdateStatusParams struct {
	Status    UserStatus `json:"status"`
	UpdatedAt time.Time  `json:"updated_at"`
	ID        int64      `json:"id"`
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
