CREATE SCHEMA users;

CREATE TABLE users (
	id		BIGSERIAL	PRIMARY KEY,
	name		VARCHAR(60)	UNIQUE,
	email		VARCHAR(254)	NOT NULL UNIQUE,
	pass		VARCHAR(60)	NOT NULL,
	salt		VARCHAR(60)	NOT NULL,
	status		INTEGER		NOT NULL,
	verification	VARCHAR(60)	NOT NULL,
	created_at		TIMESTAMP	NOT NULL DEFAULT now(),
	updated_at		TIMESTAMP	NOT NULL DEFAULT now()
);
